import { Geist, Geist_Mono } from "next/font/google";
import { ReactNode } from "react";
import type { Metadata } from "next";
import "./globals.css";
import { ProductProvider } from "@/hooks/useProducts";
import { AuthProvider } from "@/contexts/AuthContext";
import Header from "@/components/Header";
import Providers from "@/components/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AuthProvider>
            <ProductProvider>
              <Header />
              {children}
            </ProductProvider>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
